### ISSUE TITLE
报错啦 组件一个都打不开

### ISSUE THREAD

**Issue by wsq-wushiqi** [ninecat-ui/ninecat-ui#26]
如题
![4ca3625dcaea0fd83a1af83fc01a139](https://user-images.githubusercontent.com/54012796/130420720-062595f3-dd12-4ee1-abd3-d57b970bbdf1.png)

**Comment by yujie-cheng** [comment]
已修复

**Comment by yujie-cheng** [comment]
> 如题
> ![4ca3625dcaea0fd83a1af83fc01a139](https://user-images.githubusercontent.com/54012796/130420720-062595f3-dd12-4ee1-abd3-d57b970bbdf1.png)

已修复

**Comment by yujie-cheng** [comment]
md-loader问题
