### ISSUE TITLE
为什么要重复造轮子？

### ISSUE THREAD

**Issue by Baiyuetribe** [ninecat-ui/ninecat-ui#37]
以史为鉴，antdv和element由于开源早、基数广所以热度一直在。缺点是自定义主题困难，而naive-ui解决了这一刚性问题。[ninecat-ui](https://github.com/ninecat-ui/ninecat-ui)实在看不到任何突破性方案，为啥还要重复造过时的轮子？
新方向建议：
- 更先进的自定义主题方案
否则就是不可持续的，而且组件名撞车naive-ui模板语法，真好奇为啥要造这样的轮子？

**Comment by Xutaotaotao** [comment]
> 以史为鉴，antdv和element由于开源早、基数广所以热度一直在。缺点是自定义主题困难，而naive-ui解决了这一刚性问题。[ninecat-ui](https://github.com/ninecat-ui/ninecat-ui)实在看不到任何突破性方案，为啥还要重复造过时的轮子？ 新方向建议：
> 
> * 更先进的自定义主题方案
>   否则就是不可持续的，而且组件名撞车naive-ui模板语法，真好奇为啥要造这样的轮子？

naive-ui 是2021年开始的，我这个项目是2019年开始的，可以看提交记录，之前我都不知道naive-ui 项目，估计都是用N开头所以模版语法一样，只是大家设计的时候都是这么玩吧，不是重复造轮子，这个项目仅仅是为了玩玩产生的一个项目。
